language: node_js

node_js:
  - "node"

install:
  - npm install --global ionic cordova
  - npm install

script:
  - ionic build || true
  - cp -R node_modules/@ionic/app-scripts/lab www/ionic-lab
  - cp config/ionic-lab.html www/ionic-lab/index.html
  - cp config/ionic-lab.css www/ionic-lab/static/css/style.css
  - cp config/ionic-lab.js www/ionic-lab/static/js/lab.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: www
  target_branch: gh-pages

cache:
  directories:
    - 'node_modules'
    - 'www'

notifications:
  email:
    on_success: never
    on_failure: always
