language: node_js

node_js:
  - "node"

install:
  - npm install --global ionic cordova
  - npm install

script:
  - npm run build || true
  - cp -R node_modules/@ionic/app-scripts/lab www/ionic-lab

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: www
  target_branch: gh-pages

notifications:
  email:
    on_success: never
    on_failure: always
